export const OWNER_REGISTER_REQUEST = "OWNER_REGISTER_REQUEST"
export const OWNER_REGISTER_SUCCESS = "OWNER_REGISTER_SUCCESS"
export const OWNER_REGISTER_FAIL = "OWNER_REGISTER_FAIL"

export const OWNER_LOGIN_REQUEST = "OWNER_LOGIN_REQUEST"
export const OWNER_LOGIN_SUCCESS =  "OWNER_LOGIN_SUCCESS"
export const OWNER_LOGIN_FAIL = "OWNER_LOGIN_FAIL"
export const OWNER_LOGOUT = "OWNER_LOGOUT"


export const OWNER_EDITPROFILE_REQUEST = "OWNER_EDITPROFILE_REQUEST"
export const OWNER_EDITPROFILE_SUCCESS =  "OWNER_EDITPROFILE_SUCCESS"
export const OWNER_EDITPROFILE_FAIL = "OWNER_EDITPROFILE_FAIL"


export const OWNER_ADDHOMESTAY_REQUEST = "OWNER_ADDHOMESTAY_REQUEST"
export const OWNER_ADDHOMESTAY_SUCCESS =  "OWNER_ADDHOMESTAY_SUCCESS"
export const OWNER_ADDHOMESTAY_FAIL = "OWNER_ADDHOMESTAY_FAIL"


export const OWNER_ADDHOTEL_REQUEST = "OWNER_ADDHOTEL_REQUEST"
export const OWNER_ADDHOTEL_SUCCESS =  "OWNER_ADDHOTEL_SUCCESS"
export const OWNER_ADDHOTEL_FAIL = "OWNER_ADDHOTEL_FAIL"


export const OWNER_ADDCABS_REQUEST = "OWNER_ADDCABS_REQUEST"
export const OWNER_ADDCABS_SUCCESS =  "OWNER_ADDCABS_SUCCESS"
export const OWNER_ADDCABS_FAIL = "OWNER_ADDCABS_FAIL"

export const OWNER_ADDBANNER_REQUEST = "OWNER_ADDBANNER_REQUEST"
export const OWNER_ADDBANNER_SUCCESS = "OWNER_ADDBANNER_SUCCESS"
export const OWNER_ADDBANNER_FAIL = "OWNER_ADDBANNER_FAIL"