export const SUPERADMIN_LOGIN_REQUEST = "SUPERADMIN_LOGIN_REQUEST"
export const SUPERADMIN_LOGIN_SUCCESS =  "SUPERADMIN_LOGIN_SUCCESS"
export const SUPERADMIN_LOGIN_FAIL = "SUPERADMIN_LOGIN_FAIL"
export const SUPERADMIN_LOGOUT = "SUPERADMIN_LOGOUT"


export const SUPERADMIN_REGISTER_REQUEST = "SUPERADMIN_REGISTER_REQUEST"
export const SUPERADMIN_REGISTER_SUCCESS = "SUPERADMIN_REGISTER_SUCCESS"
export const SUPERADMIN_REGISTER_FAIL = "SUPERADMIN_REGISTER_FAIL"

export const SUPERADMIN_ADDDEST_REQUEST = "SUPERADMIN_ADDDEST_REQUEST"
export const SUPERADMIN_ADDDEST_SUCCESS = "SUPERADMIN_ADDDEST_SUCCESS"
export const SUPERADMIN_ADDDEST_FAIL = "SUPERADMIN_ADDDEST_FAIL"

export const SUPERADMIN_ADDBANNER_REQUEST = "SUPERADMIN_ADDBANNER_REQUEST"
export const SUPERADMIN_ADDBANNER_SUCCESS = "SUPERADMIN_ADDBANNER_SUCCESS"
export const SUPERADMIN_ADDBANNER_FAIL = "SUPERADMIN_ADDBANNER_FAIL"

