export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS =  "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"


export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_EDITPROFILE_REQUEST = "USER_EDTPROFILE_REQUEST"
export const USER_EDITPROFILE_SUCCESS = "USER_EDTPROFILE_SUCCESS"
export const USER_EDITPROFILE_FAIL = "USER_EDTPROFILE_FAIL"

export const USER_GETFILTEREDDATA_REQUEST = "USER_GETFILTEREDDATA_REQUEST"
export const USER_GETFILTEREDDATA_SUCCESS = "USER_GETFILTEREDDATA_SUCCESS"
export const USER_GETFILTEREDDATA_FAIL = "USER_GETFILTEREDDATA_FAIL"

